apiVersion: v1
kind: Service
metadata:
  name: demo-spring-service
  namespace: default
  labels:
    app: demo-spring
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  selector:
    app: demo-spring
  type: LoadBalancer