apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-spring
  labels:
    app: demo-spring
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-spring
  template:
    metadata:
      labels:
        app: demo-spring
    spec:
      containers:
      - name: demo-spring
        image: asia.gcr.io/mineral-hangar-288307/demo-spring@sha256:2628ae224d599b9c936387940163281630b21f38bf6c51be7476d44b1c8f081e